---
driver:
  name: vagrant
  vm_hostname: false

  network:
  - ["private_network", { ip: "192.168.66.66" }]
  - ["forwarded_port", { guest: "80", host: "8080" }]
  - ["forwarded_port", { guest: "8000", host: "8100" }]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[skf-workshop-chef::default]
    attributes:
